### ISSUE TITLE
각 feature 별 DTO 클래스 패키지 경로

### ISSUE THREAD

**Issue by KimJaea** [EnjoyTrip16/EnjoyTrip_Spring#13]
지금까지 develop 브랜치에 merge된 브랜치는 아래의 세 개로, 각 feature의 DTO 클래스 패키지 경로 형식이 서로 다릅니다.

[EnjoyTrip_Spring/src/main/java/com/enjoytrip](https://github.com/EnjoyTrip16/EnjoyTrip_Spring/tree/develop/src/main/java/com/enjoytrip) 경로 안에
- user/dto (feat/user 브랜치)
- hotplace/dto (feat/hotplace 브랜치)
- dto/attraction (feature/attraction 브랜치)

추후 원활한 프로젝트 진행을 위해 패키지 경로 형식을 맞췄으면 합니다.

dto 혹은 dao 등의 공통 구현 부 안에 각 feature를 넣는 방식으로 수정했으면 하는데 상재님 의견이 궁금합니다.

예시)
dto/user
dto/hotplace
dto/attraction

**Comment by sj7699** [comment]
저도 두번째 방식이 좋은 것 같습니다.

저희 프로젝트에서는 Mybatis를 사용하므로 DTO AliasPackages 디렉터리를 지정할때 그리고 Mapper scan 상위 패키지를 정할때 편할것 같고 또한 차후에 DAO가 늘어나거나 DTO가 늘어날때 확장에서도 설정파일 변경없이 파일만 추가하여 확장에 좋을 것 같습니다.

**Comment by KimJaea** [comment]
알겠습니다, 그러면 저희 패키지 경로는 두 번째 방식으로 하겠습니다.

이미 만들어진 패키지 경로는 수정해 주시고 앞으로 새 패키지 경로 생성 시 위와 같이 작성해 주시기 바랍니다.
